"""empty message

Revision ID: 7f98f847539c
Revises: 
Create Date: 2017-08-08 15:47:40.988896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f98f847539c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('pk_user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('my_turn', sa.Boolean(), nullable=True),
    sa.Column('fk_lobby', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_lobby'], ['lobby.pk_lobby'], ),
    sa.PrimaryKeyConstraint('pk_user_id')
    )
    op.add_column(u'lobby', sa.Column('num_players', sa.Integer(), nullable=True))
    op.drop_column(u'lobby', 'player2')
    op.drop_column(u'lobby', 'is_full')
    op.drop_column(u'lobby', 'player1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'lobby', sa.Column('player1', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column(u'lobby', sa.Column('is_full', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column(u'lobby', sa.Column('player2', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column(u'lobby', 'num_players')
    op.drop_table('user')
    # ### end Alembic commands ###
