"""empty message

Revision ID: faeb52060099
Revises: 
Create Date: 2018-07-29 23:12:26.560071

"""
from alembic import op
from server.models import mutables
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faeb52060099'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lobby',
    sa.Column('pk_lobby', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pk_lobby')
    )
    op.create_table('moves',
    sa.Column('pk_move_id', sa.Integer(), nullable=False),
    sa.Column('board', mutables.JsonEncodedDict(), nullable=True),
    sa.Column('turn', sa.String(), nullable=True),
    sa.Column('fk_lobby', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_lobby'], ['lobby.pk_lobby'], ),
    sa.PrimaryKeyConstraint('pk_move_id')
    )
    op.create_table('user',
    sa.Column('pk_user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('ipv4_address', sa.String(), nullable=True),
    sa.Column('my_turn', sa.Boolean(), nullable=True),
    sa.Column('fk_lobby', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_lobby'], ['lobby.pk_lobby'], ),
    sa.PrimaryKeyConstraint('pk_user_id'),
    sa.UniqueConstraint('ipv4_address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('moves')
    op.drop_table('lobby')
    # ### end Alembic commands ###
